### PR TITLE
added command argument

### PR DESCRIPTION
**Pull request by sowmyar64**
1)added os and sys module
2)added input and output file paths from command-line arguments

### CODE REVIEW

**Review by abhi-octobit8 — COMMENTED** [review]
Do the changes in the same file.

**Comment by sowmyar64** [comment]
1)Done changes in same file
2)added os and sys module
3)added input and output file paths from command-line arguments

**Review by abhi-octobit8 — APPROVED** [review]
All OK

**Review by abhi-octobit8 — APPROVED** [review]
All OK

**Pull request merged**
